# Clase 01: Regresion Lineal

## Indice
- Preambulo
    - Linealidad
    - Algebra Lineal
        - Vectores y Matrices
        - Producto interno
            - producto interno vs producto punto 
            - Proyección
    - Calculo
        - Derivada en una dimension
        - Regla de la cadena
        - Derivadas parciales
        - Gradiente
    - Optimización
        - Minimización/Maximización a traves de derivadas
            - 1 D
        - Minimización/Maximización a traves de derivadas parciales
            - 2D+ (Gradiente como aparece y se usa)
    


### Linealidad

Definición (1):
un mapa $f: U \rightarrow V$, donde $U$ y $V$ son espacios vectoriales, se denomina lineal si cumple con las siguientes propiedades:
1. Dado $\mathbf{x}$, $\mathbf{y}\in U$: $f(x+y) = f(x) + f(y)$
2. Dado $\alpha \in \mathbb{R}$: $f(\alpha x) = \alpha f(x)$

In [12]:
def f(x: int):
    return 2*x

print (f"f(3 + 2) = f(3) + f(2) =>  {f(3+2)} = {f(3)} + {f(2)}")


f(3 + 2) = f(3) + f(2) =>  10 = 6 + 4


In [27]:
def f(x):
    return x**2
print (f"f(3 + 2) != f(3) + f(2) =>  {f(3+2)} != {f(3)} + {f(2)}")

f(3 + 2) != f(3) + f(2) =>  25 != 9 + 4


## Algebra Lineal

### Vectores y Matrices

Los vectores y matrices son elementos fundamentales del algebra lineal.
Para poder desarrollar el curso de Deep Learning necesitaremos responder estas tres preguntas:
- como se operan estos objetos?
- que propiedades tienen?
- que representan en terminos de información? o porque se utilizan para representar datos?

Los Vectores y Matrices se utilizan bajo el contexto de espacio vectorial real (Utilizaremos numeros reales $\mathbb{R}$)
Un espacio para considerase vectorial debe cumplir con 10 axiomas:

1. Cerradura bajo la suma: si $\mathbf{x} \in V$ y  $\mathbf{y} \in V$ entonces $\mathbf{x} + \mathbf{y} \in V$
2. Asociatividad de la suma de vectores: $(\mathbf{x} + \mathbf{y}) + \mathbf{z} = \mathbf{x} + (\mathbf{y} + \mathbf{z})$
3. Existe un vector/matriz $0$ tal que para todo $\mathbf{x} \in V$, $\mathbf{x} + 0 = 0 + \mathbf{x} = \mathbf{x}$
4. Conmutatividad de la suma de vectores: $\mathbf{x} + \mathbf{y} = \mathbf{y} + \mathbf{x}$
5. Cerradura en la multiplicación de escalares: $\alpha \cdot \mathbf{x} \in V$, tal que $\alpha \in \mathbb{R}$ y $\mathbf{x} \in V$
6. Distribucion de suma de escalares: $(\alpha + \beta) \cdot \mathbf{x} = \alpha \cdot \mathbf{x} + \beta \cdot \mathbf{x}$ tal que $\alpha$ , $\beta \in \mathbb{R}$, y $\mathbf{x} \in V$
7. Distribución de suma vectorial: $\alpha \cdot (\mathbf{x} + \mathbf{y}) = \alpha \cdot \mathbf{x} + \alpha \cdot \mathbf{y}$ tal que $\alpha \in \mathbb{R}$, y $\mathbf{x}$, $\mathbf{y} \in V$
8. Distribución de escalares: $\alpha \cdot (\beta + \gamma) = \alpha \cdot \beta + \alpha \cdot \gamma$ tal que $\alpha, \beta, \gamma \in \mathbb{R}$.
9. Ley asociativa de multiplicacion por escalares: $\alpha \cdot (\beta \cdot \mathbf{x}) = (\alpha \cdot \beta) \cdot \mathbf{x}$ tal que $\alpha, \beta \in \mathbb{R}$, y $\mathbf{x} \in V$
10. Identico multiplicativo escalar: para cada vector $\mathbf{x} \in V$, 1 $\cdot \mathbf{x} = \mathbf{x}$ tal que $\mathbf{x} \in V$

Ej:
- El espacio de vectores de dimension $n$, tambien escrito como $\mathbb{R}^{n}$ cumple con los axiomas
- El espacio de Matrices de dimension $n \times n$, tambien escrito como $\mathbb{R}^{n \times n}$ cumple con los axiomas

Las Matrices se pueden pensar como funciones lineales, es decir cumplen con la definicion de linealidad vista anteriormente.

In [28]:
import numpy as np
def f(x: np.array):
    m = np.array([[1,2],[3,4]])
    return m@x

x = np.array([[1], [1]])
y = np.array([[-1], [-1]])

print(f"f(x+y) = f(x) + f(y)")
print(f"{f(x+y)}")
print(f"f(x):\n {f(x)}")
print(f"f(y):\n {f(y)}")
# Imprimir bonito

f(x+y) = f(x) + f(y)
[[0]
 [0]]
f(x):
 [[3]
 [7]]
f(y):
 [[-3]
 [-7]]


#### Operaciones sobre vectores y matrices

- Las matrices o funciones que transforman nuestros vectores.
- Las matrices ademas contienen información de nuestros datos (mas adelante veremos como los datos son representados en la matriz)
- Existen maneras de caracterizar las matrices para medir la cantidad de información que poseen:
    - Tamaño: Se mide a traves de la norma matricial.
    - Cantidad de información: Se puede tener una nocion de la cantidad de información contando la cantidad de auto valores diferentes de cero.
    - Como una matriz transforma un vector?: se puede saber como una matriz estire/comprime o rota a un vector a traves de sus espacios fundamentales (SVD)
 
Por ahora nos interesa entender como se hacen las operaciones fundamentales entre vectores y matrices:
1. Suma de matrices
2. Suma de vectores
3. Multiplicar matriz por escalar
4. Multiplicar vector por escalar
5. Poducto interno entre vectores
6. Producto matriz/vector
7. Producto de matrices