### Introducción a NumPy

NumPy es una biblioteca central en Python utilizada para la computación científica. Proporciona un objeto de array multidimensional, y es esencial para el manejo de datos numéricos y la realización de operaciones matemáticas complejas.

#### Importando NumPy

Para comenzar a utilizar NumPy, primero debemos importarlo. Esto se hace comúnmente con el alias `np` para simplificar el código.


In [1]:
import numpy as np

#### Creando Arrays en NumPy

NumPy permite crear arrays de una manera muy eficiente. Vamos a explorar cómo crear diferentes tipos de arrays, incluyendo vectores fila, vectores columna, y matrices.


In [4]:
# Create a row vector
row_vector = np.array([1, 2, 3])
print("Row vector:", row_vector)

# Create a column vector
column_vector = np.array([[1], [2], [3]])
print("Column vector:\n", column_vector)

# Create a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:\n", matrix)


Row vector: [1 2 3]
Column vector:
 [[1]
 [2]
 [3]]
Matrix:
 [[1 2 3]
 [4 5 6]]


#### Dimensiones de un Array

El `shape` de un array nos dice cuántos elementos contiene en cada dimensión. Vamos a explorar esto con nuestros arrays.


In [5]:
print("Shape of row vector:", row_vector.shape)
print("Shape of column vector:", column_vector.shape)
print("Shape of matrix:", matrix.shape)


Shape of row vector: (3,)
Shape of column vector: (3, 1)
Shape of matrix: (2, 3)


La salida de `shape` proporciona información vital sobre la estructura del array. 
Por ejemplo:
- El vector fila `shape` muestra (3,), indicando que tiene 3 elementos en una dimensión.
- El vector columna muestra (3, 1), indicando 3 elementos en una dimensión y 1 en otra.
- La matriz muestra (2, 3), indicando 2 filas y 3 columnas.

#### Tensor en NumPy

Un tensor es una generalización de vectores y matrices y se puede considerar como un array de n-dimensiones. Por ejemplo:
- Un tensor de rango 0 es un escalar (un solo número).
- Un tensor de rango 1 es un vector (un arreglo de números).
- Un tensor de rango 2 es una matriz (un arreglo bidimensional de números).
- Los tensores de rango superior (3, 4, etc.) son estructuras con más dimensiones.


In [10]:
# Create a rank 3 tensor
tensor_3d = np.ones((2, 2, 2))
print("3D tensor:\n", tensor_3d)
print("Shape of 3D tensor:", tensor_3d.shape)

3D tensor:
 [[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
Shape of 3D tensor: (2, 2, 2)


Los tensores con mayor rango tienen dimensiones adicionales en su `shape`. Un tensor 3D tiene tres dimensiones en su `shape`, y un tensor 4D tiene cuatro. Estas estructuras son fundamentales en el aprendizaje profundo y otras áreas de análisis numérico.

### Creación de Tensores con Diferentes Funciones en NumPy

NumPy ofrece varias funciones para crear arrays o tensores de diferentes dimensiones. Vamos a explorar cómo podemos crear tensores 1D, 2D y 3D utilizando diferentes funciones como `ones`, `zeros`, `arange`, y otras.

#### `np.arange(stop)`
- **Signature**: `np.arange(stop)`
- **Input**:
  - `stop`: Valor final de la secuencia (el valor inicial por defecto es 0 y el paso por defecto es 1).
- **Descripción**: Genera valores equiespaciados dentro de un rango dado desde 0 hasta `stop - 1`.


In [24]:
# Ejemplo de np.arange con un solo valor
arange_single_value_example = np.arange(5)
print(f"Vector creado con np.arange:{arange_single_value_example}, shape: {arange_single_value_example.shape}\n")

# Crear una matriz usando np.arange y np.reshape
arange_matrix_example = np.arange(12).reshape(3, 4)
print(f"Matriz creada con np.arange:\n {arange_matrix_example}")
print(f"shape: {arange_matrix_example.shape}")

Vector creado con np.arange:[0 1 2 3 4], shape: (5,)

Matriz creada con np.arange:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape: (3, 4)


#### `np.linspace(start, stop, num)`
- **Signature**: `np.linspace(start, stop, num=50)`
- **Input**:
  - `start`: Valor inicial de la secuencia.
  - `stop`: Valor final de la secuencia.
  - `num`: Número de elementos generados.
- **Descripción**: Devuelve números equiespaciados dentro de un rango específico.


In [25]:
# Ejemplo de np.linspace
linspace_example = np.linspace(0, 10, 5)
print(f"Vector creado con np.linspace:{linspace_example}, shape: {linspace_example.shape}")


Vector creado con np.linspace:[ 0.   2.5  5.   7.5 10. ], shape: (5,)


#### `np.full(shape, fill_value)`
- **Signature**: `np.full(shape, fill_value)`
- **Input**:
  - `shape`: Dimensiones del array.
  - `fill_value`: Valor para llenar el array.
- **Descripción**: Crea un array con un tamaño y forma específicos, lleno de un valor dado.


In [31]:
# Ejemplo vector de np.full
vector_full = np.full((3), 10)
print(f"Vector creado np.full:\n {vector_full}")

# Ejemplo Matriz de np.full
matrix_full = np.full((2, 3), 7)
print(f"Matriz creada np.full:\n {matrix_full}")

Vector creado np.full:
 [10 10 10]
Matriz creada np.full:
 [[7 7 7]
 [7 7 7]]


#### `np.eye(N, M=None, k=0)`
- **Signature**: `np.eye(N, M=None, k=0)`
- **Input**:
  - `N`: Número de filas.
  - `M`: Número de columnas, opcional.
  - `k`: Índice de la diagonal (0 es la diagonal principal).
- **Descripción**: Devuelve una matriz 2D con unos en la diagonal y ceros en el resto.


In [34]:
# Ejemplo de np.eye
eye_example = np.eye(3)
print(f"np.eye:\n{eye_example}\n", )

# Ejemplo de np.eye
eye_example = np.eye(3, k=1)
print(f"np.eye(3, k=1):\n{eye_example}")


np.eye:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

np.eye(3, k=1):
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


#### `np.empty(shape)`
- **Signature**: `np.empty(shape)`
- **Input**:
  - `shape`: Dimensiones del array.
- **Descripción**: Crea un array sin inicializar de una forma dada. Los contenidos serán aleatorios y dependerán del estado de la memoria.


In [40]:
# Ejemplo de np.empty
empty_example = np.empty((3, 4))
print(f"np.empty:\n{empty_example}")

np.empty:
[[0.0e+000 4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323 3.5e-323]
 [4.0e-323 4.4e-323 4.9e-323 5.4e-323]]


#### `np.tile(A, reps)`
- **Signature**: `np.tile(A, reps)`
- **Input**:
  - `A`: Array de entrada.
  - `reps`: Número de repeticiones de `A` en cada dimensión.
- **Descripción**: Construye un array repitiendo `A` el número de veces especificado por `reps`.


In [42]:
# Ejemplo de np.tile
tile_example = np.tile(np.array([[1, 2], [3, 4]]), (2, 2))
print(f"np.tile:\n{tile_example}")


np.tile:
[[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]


#### `np.repeat(a, repeats, axis=None)`
- **Signature**: `np.repeat(a, repeats, axis=None)`
- **Input**:
  - `a`: Array de entrada.
  - `repeats`: Número de repeticiones de cada elemento.
  - `axis`: Eje a lo largo del cual repetir los valores.
- **Descripción**: Repite los elementos de `a` el número de veces indicado en `repeats`.


In [51]:
# Ejemplo de np.repeat
repeat_example = np.repeat(np.array([1, 2, 3]), 2, axis=0)
print(f"np.repeat:\n{repeat_example}")


np.repeat:
[1 1 2 2 3 3]


Estas herramientas de NumPy son fundamentales para la manipulación de arrays y la preparación de datos en la computación científica y el aprendizaje automático.