# Introducción a NumPy

NumPy es una biblioteca central en Python utilizada para la computación científica. Proporciona un objeto de array multidimensional, y es esencial para el manejo de datos numéricos y la realización de operaciones matemáticas complejas.

## Importando NumPy

Para comenzar a utilizar NumPy, primero debemos importarlo. Esto se hace comúnmente con el alias `np` para simplificar el código.


In [1]:
import numpy as np

## Creando Arrays en NumPy

NumPy permite crear arrays de una manera muy eficiente. Vamos a explorar cómo crear diferentes tipos de arrays, incluyendo vectores fila, vectores columna, y matrices.


In [2]:
# Create a row vector
row_vector = np.array([1, 2, 3])
print("Row vector:", row_vector)

# Create a column vector
column_vector = np.array([[1], [2], [3]])
print("Column vector:\n", column_vector)

# Create a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:\n", matrix)


Row vector: [1 2 3]
Column vector:
 [[1]
 [2]
 [3]]
Matrix:
 [[1 2 3]
 [4 5 6]]


#### Dimensiones de un Array

El `shape` de un array nos dice cuántos elementos contiene en cada dimensión. Vamos a explorar esto con nuestros arrays.


In [3]:
print("Shape of row vector:", row_vector.shape)
print("Shape of column vector:", column_vector.shape)
print("Shape of matrix:", matrix.shape)


Shape of row vector: (3,)
Shape of column vector: (3, 1)
Shape of matrix: (2, 3)


La salida de `shape` proporciona información vital sobre la estructura del array. 
Por ejemplo:
- El vector fila `shape` muestra (3,), indicando que tiene 3 elementos en una dimensión.
- El vector columna muestra (3, 1), indicando 3 elementos en una dimensión y 1 en otra.
- La matriz muestra (2, 3), indicando 2 filas y 3 columnas.

### Tensor en NumPy

Un tensor es una generalización de vectores y matrices y se puede considerar como un array de n-dimensiones. Por ejemplo:
- Un tensor de rango 0 es un escalar (un solo número).
- Un tensor de rango 1 es un vector (un arreglo de números).
- Un tensor de rango 2 es una matriz (un arreglo bidimensional de números).
- Los tensores de rango superior (3, 4, etc.) son estructuras con más dimensiones.


In [4]:
# Create a rank 3 tensor
tensor_3d = np.ones((2, 2, 2))
print("3D tensor:\n", tensor_3d)
print("Shape of 3D tensor:", tensor_3d.shape)

3D tensor:
 [[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
Shape of 3D tensor: (2, 2, 2)


Los tensores con mayor rango tienen dimensiones adicionales en su `shape`. Un tensor 3D tiene tres dimensiones en su `shape`, y un tensor 4D tiene cuatro. Estas estructuras son fundamentales en el aprendizaje profundo y otras áreas de análisis numérico.

### Creación de Tensores con Diferentes Funciones en NumPy

NumPy ofrece varias funciones para crear arrays o tensores de diferentes dimensiones. Vamos a explorar cómo podemos crear tensores 1D, 2D y 3D utilizando diferentes funciones como `ones`, `zeros`, `arange`, y otras.

#### `np.arange(stop)`
- **Signature**: `np.arange(stop)`
- **Input**:
  - `stop`: Valor final de la secuencia (el valor inicial por defecto es 0 y el paso por defecto es 1).
- **Descripción**: Genera valores equiespaciados dentro de un rango dado desde 0 hasta `stop - 1`.


In [5]:
# Ejemplo de np.arange con un solo valor
arange_single_value_example = np.arange(5)
print(f"Vector creado con np.arange:{arange_single_value_example}, shape: {arange_single_value_example.shape}\n")

# Crear una matriz usando np.arange y np.reshape
arange_matrix_example = np.arange(12).reshape(3, 4)
print(f"Matriz creada con np.arange:\n {arange_matrix_example}")
print(f"shape: {arange_matrix_example.shape}")

Vector creado con np.arange:[0 1 2 3 4], shape: (5,)

Matriz creada con np.arange:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape: (3, 4)


#### `np.linspace(start, stop, num)`
- **Signature**: `np.linspace(start, stop, num=50)`
- **Input**:
  - `start`: Valor inicial de la secuencia.
  - `stop`: Valor final de la secuencia.
  - `num`: Número de elementos generados.
- **Descripción**: Devuelve números equiespaciados dentro de un rango específico.


In [6]:
# Ejemplo de np.linspace
linspace_example = np.linspace(0, 10, 5)
print(f"Vector creado con np.linspace:{linspace_example}, shape: {linspace_example.shape}")


Vector creado con np.linspace:[ 0.   2.5  5.   7.5 10. ], shape: (5,)


#### `np.full(shape, fill_value)`
- **Signature**: `np.full(shape, fill_value)`
- **Input**:
  - `shape`: Dimensiones del array.
  - `fill_value`: Valor para llenar el array.
- **Descripción**: Crea un array con un tamaño y forma específicos, lleno de un valor dado.


In [7]:
# Ejemplo vector de np.full
vector_full = np.full((3), 10)
print(f"Vector creado np.full:\n {vector_full}")

# Ejemplo Matriz de np.full
matrix_full = np.full((2, 3), 7)
print(f"Matriz creada np.full:\n {matrix_full}")

Vector creado np.full:
 [10 10 10]
Matriz creada np.full:
 [[7 7 7]
 [7 7 7]]


#### `np.eye(N, M=None, k=0)`
- **Signature**: `np.eye(N, M=None, k=0)`
- **Input**:
  - `N`: Número de filas.
  - `M`: Número de columnas, opcional.
  - `k`: Índice de la diagonal (0 es la diagonal principal).
- **Descripción**: Devuelve una matriz 2D con unos en la diagonal y ceros en el resto.


In [8]:
# Ejemplo de np.eye
eye_example = np.eye(3)
print(f"np.eye:\n{eye_example}\n", )

# Ejemplo de np.eye
eye_example = np.eye(3, k=1)
print(f"np.eye(3, k=1):\n{eye_example}")


np.eye:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

np.eye(3, k=1):
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


#### `np.empty(shape)`
- **Signature**: `np.empty(shape)`
- **Input**:
  - `shape`: Dimensiones del array.
- **Descripción**: Crea un array sin inicializar de una forma dada. Los contenidos serán aleatorios y dependerán del estado de la memoria.


In [9]:
# Ejemplo de np.empty
empty_example = np.empty((3, 4))
print(f"np.empty:\n{empty_example}")

np.empty:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### `np.tile(A, reps)`
- **Signature**: `np.tile(A, reps)`
- **Input**:
  - `A`: Array de entrada.
  - `reps`: Número de repeticiones de `A` en cada dimensión.
- **Descripción**: Construye un array repitiendo `A` el número de veces especificado por `reps`.


In [10]:
# Ejemplo de np.tile
tile_example = np.tile(np.array([[1, 2], [3, 4]]), (2, 2))
print(f"np.tile:\n{tile_example}")


np.tile:
[[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]


#### `np.repeat(a, repeats, axis=None)`
- **Signature**: `np.repeat(a, repeats, axis=None)`
- **Input**:
  - `a`: Array de entrada.
  - `repeats`: Número de repeticiones de cada elemento.
  - `axis`: Eje a lo largo del cual repetir los valores.
- **Descripción**: Repite los elementos de `a` el número de veces indicado en `repeats`.


In [11]:
# Ejemplo de np.repeat
repeat_example = np.repeat(np.array([1, 2, 3]), 2, axis=0)
print(f"np.repeat:\n{repeat_example}")


np.repeat:
[1 1 2 2 3 3]


Estas herramientas de NumPy son fundamentales para la manipulación de arrays y la preparación de datos en la computación científica y el aprendizaje automático.

## Manipulación de la Forma de Arrays y Matrices

La manipulación de la forma de arrays y matrices es una tarea común en análisis de datos y machine learning. 
Utilizamos diferentes funciones en NumPy para cambiar la estructura de los arrays y matrices, 
lo cual nos permite preparar los datos para el análisis o ajustarlos a las necesidades de entrada/salida de los algoritmos de machine learning.

### Uso de `np.reshape()`

La función `np.reshape()` nos permite cambiar la forma de un array o matriz sin cambiar sus datos. 
Es útil para reorganizar un conjunto de datos en una estructura deseada.

Veamos cómo podemos cambiar la forma de un array unidimensional a una matriz bidimensional o cambiar el tamaño de una matriz.


In [43]:
# Creando un array unidimensional
array = np.arange(1, 10)  # Un array de 1 a 9
print("Array Original:")
print(array)

# Cambiando la forma a una matriz 3x3
matrix = array.reshape(3, 3)
print("\\nMatriz Bidimensional:")
print(matrix)


Array Original:
[1 2 3 4 5 6 7 8 9]
\nMatriz Bidimensional:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Indexación y Slicing en Vectores y Matrices

En esta sección, exploraremos cómo acceder a elementos específicos y secciones en vectores y matrices utilizando NumPy. La indexación y el slicing son técnicas fundamentales en Python y NumPy, permitiéndonos seleccionar elementos individuales o subconjuntos de datos de estructuras más grandes.

### Indexación en NumPy
La indexación nos permite acceder a un elemento específico dentro de un array de NumPy.


In [12]:

# Creando un vector y accediendo a un elemento
vector = np.array([1, 2, 3, 4, 5])
print("Elemento en la posición 2:", vector[2])

# Creando una matriz y accediendo a un elemento
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Elemento en la fila 1, columna 2:", matrix[1, 2])


Elemento en la posición 2: 3
Elemento en la fila 1, columna 2: 6


### Slicing en NumPy
El slicing nos permite acceder a secuencias de datos dentro del array.


In [14]:
# Accediendo a una parte del vector
print("Elementos del índice 1 al 3:", vector[1:4])

# Accediendo a filas y columnas específicas en la matriz
print("Primera fila:", matrix[0, :])
print("Segunda columna:", matrix[:, 1])

# Obteniendo una submatriz
print("Submatriz con las primeras 2 filas y columnas:\n", matrix[:2, :2])


Elementos del índice 1 al 3: [2 3 4]
Primera fila: [1 2 3]
Segunda columna: [2 5 8]
Submatriz con las primeras 2 filas y columnas:
 [[1 2]
 [4 5]]


## Operaciones Matemáticas y Algebraicas con NumPy

En esta sección, exploraremos cómo realizar operaciones matemáticas y algebraicas básicas usando NumPy, una de las bibliotecas más fundamentales en Python para la computación científica. Aprenderás a manejar vectores y matrices, realizar operaciones elemento a elemento, y aplicar conceptos de álgebra lineal esenciales para el análisis de datos y el modelado matemático.

### Operaciones Elemento a Elemento en Vectores y Matrices

NumPy permite realizar operaciones matemáticas elemento a elemento en vectores y matrices de manera eficiente y sencilla. Esto incluye suma, resta, multiplicación por escalar, y división. Vamos a ver cómo se pueden llevar a cabo estas operaciones.

### Operaciones Elemento a Elemento en Vectores


In [15]:
# Crear dos vectores de ejemplo
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

# Suma elemento a elemento
suma = vector_a + vector_b
print("Suma:", suma)

# Resta elemento a elemento
resta = vector_a - vector_b
print("Resta:", resta)

# Multiplicación por escalar
escalar = 2
multiplicacion_escalar = vector_a * escalar
print("Multiplicación por escalar:", multiplicacion_escalar)

# División elemento a elemento
division = vector_a / vector_b
print("División:", division)


Suma: [5 7 9]
Resta: [-3 -3 -3]
Multiplicación por escalar: [2 4 6]
División: [0.25 0.4  0.5 ]


### Operaciones Elemento a Elemento en Matrices

In [16]:
# Crear dos matrices de ejemplo
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

# Suma elemento a elemento
suma_matrices = matrix_a + matrix_b
print("Suma de matrices:\n", suma_matrices)

# Resta elemento a elemento
resta_matrices = matrix_a - matrix_b
print("Resta de matrices:\n", resta_matrices)

# Multiplicación elemento a elemento
multiplicacion_matrices = matrix_a * matrix_b
print("Multiplicación elemento a elemento:\n", multiplicacion_matrices)

# División elemento a elemento
division_matrices = matrix_a / matrix_b
print("División elemento a elemento:\n", division_matrices)

Suma de matrices:
 [[ 6  8]
 [10 12]]
Resta de matrices:
 [[-4 -4]
 [-4 -4]]
Multiplicación elemento a elemento:
 [[ 5 12]
 [21 32]]
División elemento a elemento:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


### Multiplicación de Matrices con Vectores

La multiplicación de matrices con vectores es un caso especial de la multiplicación de matrices, esencial en muchas aplicaciones matemáticas y computacionales. Comprender cómo se realiza esta operación y la dimensión del resultado es crucial para la correcta aplicación de conceptos de álgebra lineal.

#### Multiplicación Matriz-Vector Columna

Si tenemos una matriz $A$ de tamaño $m \times n$ y multiplicamos por un vector columna $B$ de tamaño $n \times 1$, el resultado será un vector columna $C$ de tamaño $m \times 1$. La operación se representa como:

  $$
  A_{m \times n} \times B_{n \times 1} = C_{m \times 1}
  $$

  Donde $A$ es una matriz de $m$ filas y $n$ columnas, $B$ es un vector columna de $n$ filas, y $C$ es el vector resultado de $m$ filas.
  
  **Es fundamental verificar que las dimensiones sean compatibles para la multiplicación, asegurando que el número de columnas en el primer operando sea igual al número de filas en el segundo operando.**

Consideremos una matriz $A$ de tamaño $2 \times 3$ y un vector columna $B$ de tamaño $3 \times 1$:

  $$
  A = \begin{pmatrix}
  a_{11} & a_{12} & a_{13} \\
  a_{21} & a_{22} & a_{23}
  \end{pmatrix},
  B = \begin{pmatrix}
  b_{11} \\
  b_{21} \\
  b_{31}
  \end{pmatrix}
  $$

  La multiplicación se realiza como:

  $$
  AB = \begin{pmatrix}
  a_{11} \cdot b_{11} + a_{12} \cdot b_{21} + a_{13} \cdot b_{31} \\
  a_{21} \cdot b_{11} + a_{22} \cdot b_{21} + a_{23} \cdot b_{31}
  \end{pmatrix}
  $$

  El resultado es un vector columna de tamaño $2 \times 1$, correspondiente al número de filas de la matriz $A$.

In [26]:
# Definir un vector como vector columna
vector_column = np.array([[1], [2], [3]])
matrix = np.array([[3, 3, 3], [5, 6, 7]])

# Multiplicación de la matriz por el vector columna
result_colum = np.dot(matrix, vector_column)
print("Resultado de la multiplicación matriz-vector columna:\n", result_colum)


Resultado de la multiplicación matriz-vector columna:
 [[18]
 [38]]


#### Multiplicación Matriz-Vector Fila

Si multiplicamos un vector fila $D$ de tamaño $1 \times m$ por una matriz $E$ de tamaño $m \times n$, el resultado será un vector fila $F$ de tamaño $1 \times n$. Esta operación se representa como:

  $$
  D_{1 \times m} \times E_{m \times n} = F_{1 \times n}
  $$

  Aquí, $D$ es un vector fila de $m$ columnas, $E$ es una matriz de $m$ filas y $n$ columnas, y $F$ es el vector resultado de $n$ columnas.

**Es fundamental verificar que las dimensiones sean compatibles para la multiplicación, asegurando que el número de columnas en el primer operando sea igual al número de filas en el segundo operando.**

Consideremos un vector fila $D$ de tamaño $1 \times 2$ y una matriz $E$ de tamaño $2 \times 3$:

  $$
  D = \begin{pmatrix}
  d_{11} & d_{12}
  \end{pmatrix},
  E = \begin{pmatrix}
  e_{11} & e_{12} & e_{13} \\
  e_{21} & e_{22} & e_{23}
  \end{pmatrix}
  $$

  La multiplicación se calcula como:

  $$
  DE = \begin{pmatrix}
  d_{11} \cdot e_{11} + d_{12} \cdot e_{21} & d_{11} \cdot e_{12} + d_{12} \cdot e_{22} & d_{11} \cdot e_{13} + d_{12} \cdot e_{23}
  \end{pmatrix}
  $$

  El resultado es un vector fila de tamaño $1 \times 3$, que es el número de columnas de la matriz $E$.


In [32]:
# Definir un vector como vector fila
vector_row = np.array([1, 2])
matrix = np.array([[3, 3, 3], [4, 4, 4]])

# Multiplicación de la matriz por el vector fila
result_row = np.dot(vector_row, matrix)
print("Resultado de la multiplicación matriz-vector fila:\n", result_row)


Resultado de la multiplicación matriz-vector fila:
 [11 11 11]


#### Multiplicación de Matrices

Consideremos dos matrices $A$ de tamaño $2 \times 3$ y $B$ de tamaño $3 \times 2$:

$$
A = \begin{pmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23}
\end{pmatrix},
B = \begin{pmatrix}
b_{11} & b_{12} \\
b_{21} & b_{22} \\
b_{31} & b_{32}
\end{pmatrix}
$$

La multiplicación de $A$ por $B$ se calcula como sigue:

$$
AB = \begin{pmatrix}
a_{11} \cdot b_{11} + a_{12} \cdot b_{21} + a_{13} \cdot b_{31} & a_{11} \cdot b_{12} + a_{12} \cdot b_{22} + a_{13} \cdot b_{32} \\
a_{21} \cdot b_{11} + a_{22} \cdot b_{21} + a_{23} \cdot b_{31} & a_{21} \cdot b_{12} + a_{22} \cdot b_{22} + a_{23} \cdot b_{32}
\end{pmatrix}
$$

El resultado es una nueva matriz $C$ de tamaño $2 \times 2$, donde cada elemento $c_{ij}$ de $C$ es el resultado de la suma de los productos de los elementos correspondientes de la fila $i$ de $A$ y la columna $j$ de $B$. Esto muestra que el tamaño resultante de la multiplicación de matrices es determinado por el número de filas de la primera matriz y el número de columnas de la segunda matriz. En este caso, dado que $A$ es $2 \times 3$ y $B$ es $3 \times 2$, el resultado $C$ es una matriz $2 \times 2$.


In [33]:
# Definir dos matrices
matrix_a = np.array([[1, 2, 3], [4, 5, 6]])
matrix_b = np.array([[7, 8], [9, 10], [11, 12]])

# Multiplicación de las matrices
result_matrix = np.dot(matrix_a, matrix_b)
print("Resultado de la multiplicación de matrices:\n", result_matrix)


Resultado de la multiplicación de matrices:
 [[ 58  64]
 [139 154]]


## Álgebra Lineal en NumPy

Ahora, profundizaremos en operaciones de álgebra lineal que son fundamentales para la ciencia de datos y el machine learning. Utilizaremos el submódulo `np.linalg` de NumPy para realizar operaciones como multiplicación de matrices, cálculo de determinantes, inversas de matrices, y encontrar autovalores y autovectores.

### Operaciones esenciales

Estas operaciones son esenciales en el álgebra lineal y tienen muchas aplicaciones en la resolución de sistemas de ecuaciones, análisis de estabilidad, y más.

#### Transposición de Matrices

La transposición de una matriz es una operación que intercambia filas por columnas en la matriz. Dada una matriz  $A$, su transpuesta, denotada como $A^T$, se forma intercambiando los elementos de las filas por las columnas correspondientes.

La transposición es fundamental en muchas aplicaciones de álgebra lineal y análisis de datos, ya que a menudo necesitamos ajustar la orientación de los datos para realizar cálculos o facilitar ciertas operaciones.

Consideremos la siguiente matriz $A$ y su transpuesta $A^T$:

$$
A = \begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix}
\quad
A^T = \begin{pmatrix}
1 & 3 \\
2 & 4
\end{pmatrix}
$$

Podemos calcular la transpuesta de $A$ utilizando NumPy:


In [42]:
# Matriz B
A = np.array([[7, 8], [9, 10], [11, 12]])
print("Matriz Original A:\n", A)
# Transpuesta de B
A_t = A.T
print("Matriz Transpuesta A^T:\n", A_t)

Matriz Original A:
 [[ 7  8]
 [ 9 10]
 [11 12]]
Matriz Transpuesta A^T:
 [[ 7  9 11]
 [ 8 10 12]]


#### Determinante de una Matriz

El determinante es una propiedad numérica que se puede calcular de una matriz cuadrada. Proporciona información importante sobre la matriz, como si tiene inversa (una matriz es invertible si y solo si su determinante no es cero). El determinante de una matriz de $2 \times 2$ se calcula como el producto de los elementos en la diagonal principal menos el producto de los elementos en la diagonal secundaria.

Consideremos una matriz $A$ de tamaño $2 \times 2$:

$$
A = \begin{pmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{pmatrix}
$$

El determinante de $A$ se calcula usando la siguiente fórmula:

$$
\text{det}(A) = a_{11} \cdot a_{22} - a_{12} \cdot a_{21}
$$

El determinante proporciona información crucial sobre la matriz, como su invertibilidad y propiedades relacionadas con el volumen en transformaciones lineales.

Ahora, veamos cómo calcular el determinante de una matriz usando NumPy en Python:


In [38]:
# Cálculo del determinante de una matriz
matrix = np.array([[-1, 5], [3, 4]])
determinant = np.linalg.det(matrix)
print("Determinante:", determinant)

Determinante: -18.999999999999996


#### Inversa de una Matriz

La inversa de una matriz cuadrada $A$ es otra matriz, denotada como $A^{-1}$, tal que la multiplicación de $A$ por $A^{-1}$ (en cualquier orden) da como resultado la matriz identidad $I$. Esto es, $AA^{-1} = A^{-1}A = I$. La existencia de una inversa es indicativa de la invertibilidad de la matriz, que está directamente relacionada con la propiedad de que el determinante de la matriz no es cero.

Para calcular la inversa de una matriz, primero debemos asegurarnos de que la matriz sea cuadrada (número de filas igual al número de columnas) y su determinante no sea cero.

Consideremos la siguiente matriz $A$ para el ejemplo:

$$
A = \begin{pmatrix}
1 & 2 & 3 \\
0 & 1 & 4 \\
5 & 6 & 0
\end{pmatrix}
$$

Podemos calcular la inversa de $A$ usando NumPy:

In [39]:
# Definir la matriz
A = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])

# Cálculo de la inversa de una matriz
inv = np.linalg.inv(A)
print("Inversa de la matriz:\n", inv)


Inversa de la matriz:
 [[-0.21052632  0.26315789]
 [ 0.15789474  0.05263158]]


### Autovalores y Autovectores

Los autovalores y autovectores son conceptos fundamentales en álgebra lineal, con aplicaciones importantes en análisis de estabilidad, mecánica cuántica, análisis de componentes principales (PCA), entre otros. Los autovalores son escalares asociados a una matriz cuadrada que, junto con sus autovectores correspondientes, revelan propiedades esenciales de la matriz.

Consideremos una matriz cuadrada $A$. Un escalar $\lambda$ es un autovalor de $A$ si existe un vector no nulo $v$ tal que:

$$
Av = \lambda v
$$

En esta ecuación, $v$ es un autovector de $A$ correspondiente al autovalor $\lambda$. Intuitivamente, esta ecuación dice que la multiplicación de $A$ por $v$ resulta en un vector que es un múltiplo escalar de $v$, donde el factor de multiplicación es $\lambda$.

Vamos a calcular los autovalores y autovectores de una matriz usando NumPy en Python:

In [41]:
# Cálculo de autovalores y autovectores
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Autovalores:", eigenvalues)
print("Autovectores:\n", eigenvectors)


Autovalores: [-3.10977223  6.10977223]
Autovectores:
 [[-0.92133794 -0.57524923]
 [ 0.38876264 -0.81797819]]


### Diagonal de una Matriz

La diagonal de una matriz $A$ está compuesta por los elementos $a_{ij}$ donde $i = j$. Es decir, son los elementos que se encuentran en la línea que va desde la esquina superior izquierda hasta la esquina inferior derecha de la matriz.

Para una matriz cuadrada $A$ de tamaño $n \times n$, representada como:

$$
A = \begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} & a_{n2} & \cdots & a_{nn}
\end{pmatrix}
$$

Su diagonal principal se puede representar como:

$$
\text{diag}(A) = \begin{pmatrix}
a_{11} \\
a_{22} \\
\vdots \\
a_{nn}
\end{pmatrix}
$$

La diagonal principal de una matriz es importante en varios aspectos del álgebra lineal y el análisis numérico, como el cálculo de trazas y determinantes, y juega un papel crucial en la teoría espectral de matrices.

En NumPy, podemos extraer la diagonal principal de una matriz utilizando la función `np.diag()`. Veamos cómo se hace esto con una matriz genérica $A$.


In [46]:
# Creando una matriz bidimensional
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matriz Original A:")
print(A)

# Extrayendo la diagonal principal
diag_A = np.diag(A)
print("\\nDiagonal principal de A:")
print(diag_A)

Matriz Original A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
\nDiagonal principal de A:
[1 5 9]


La función `np.diag()` tiene un doble propósito: cuando se le proporciona una matriz, devuelve la diagonal principal, y cuando se le proporciona un array unidimensional, crea una matriz cuadrada con ese array en la diagonal principal y ceros en todas las demás posiciones. Esto facilita la construcción de matrices a partir de sus diagonales y viceversa.

In [47]:
# Creando una matriz cuadrada usando np.diag() con un array unidimensional
new_matrix = np.diag(diag_A)
print("\\nNueva Matriz con la diagonal de A:")
print(new_matrix)

\nNueva Matriz con la diagonal de A:
[[1 0 0]
 [0 5 0]
 [0 0 9]]
